steps:
  # pull cached image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/bs-node:latest || exit 0"
  # build final image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "BS_PLATFORM_VERSION=7.1.1",
        "--tag",
        "gcr.io/$PROJECT_ID/bs-node:$SHORT_SHA",
        "--tag",
        "gcr.io/$PROJECT_ID/bs-node:latest",
        "--cache-from",
        "gcr.io/$PROJECT_ID/bs-node:latest",
        ".",
      ]
    timeout: 1200s
timeout: 1400s
images:
  [
    "gcr.io/$PROJECT_ID/bs-node:latest",
    "gcr.io/$PROJECT_ID/bs-node:$SHORT_SHA",
  ]
