version: "3.7"

services:
  bs-node:
    image: gcr.io/tech-resume/bs-node
    build:
      context: .
      args:
        BS_PLATFORM_VERSION: 7.0.1
  web:
    env_file:
      - .env
    command: sh ./scripts/startup.sh
    container_name: web
    build:
      context: ./web
      target: builder
      args:
        - GATSBY_API_SCHEME=http
        - GATSBY_API_HOST=127.0.0.1:3000
    volumes:
      - ./web/src:/home/node/app/src:cached
      - ./web/scripts:/home/node/app/scripts:cached
      - ./web/package.json:/home/node/app/package.json:cached
      - ./web/yarn.lock:/home/node/app/yarn.lock:cached
      - ./web/bsconfig.json:/home/node/app/bsconfig.json:cached
      - ./web/gatsby-browser.js:/home/node/app/gatsby-browser.js:cached
      - ./web/gatsby-config.js:/home/node/app/gatsby-config.js:cached
      - ./web/gatsby-node.js:/home/node/app/gatsby-node.js:cached
      - ./web/gatsby-ssr.js:/home/node/app/gatsby-ssr.js:cached
      - ./web/jest.config.js:/home/node/app/jest.config.js:cached
      - ./web/babel.config.js:/home/node/app/babel.config.js:cached
    ports:
      - "8000:8000"
  api:
    env_file:
      - .env
    command: sh ./scripts/startup.sh
    container_name: api
    build:
      context: ./api
      args:
        - SCHEME=http
        - HOST=127.0.0.1
        - PORT=3000
    volumes:
      - ./api/src:/home/node/app/src:cached
      - ./api/scripts:/home/node/app/scripts:cached
      - ./api/package.json:/home/node/app/package.json:cached
      - ./api/yarn.lock:/home/node/app/yarn.lock:cached
      - ./api/nodemon.json:/home/node/app/nodemon.json:cached
      - ./api/bsconfig.json:/home/node/app/bsconfig.json:cached
    ports:
      - "3000:3000"
      - "3001:3001"
  pdfgen:
    privileged: true
    env_file:
      - .env
    command: sh ./scripts/startup.sh
    build:
      context: ./pdfgen
    container_name: pdfgen
    volumes:
      - ./pdfgen/src:/home/node/app/src:cached
      - ./pdfgen/scripts:/home/node/app/scripts:cached
      - ./pdfgen/package.json:/home/node/app/package.json:cached
      - ./pdfgen/yarn.lock:/home/node/app/yarn.lock:cached
      - ./pdfgen/nodemon.json:/home/node/app/nodemon.json:cached
      - ./pdfgen/bsconfig.json:/home/node/app/bsconfig.json:cached
    ports:
      - "4000:4000"
      - "4001:4001"
