version: "3.7"

services:
  bs-node:
    image: gcr.io/tech-resume/bs-node
    build:
      context: .
      args:
        BS_PLATFORM_VERSION: 7.1.1
  web:
    # truthy *tty* is necessary in order to get colored bsb output
    tty: true
    command: sh ./scripts/startup.sh
    container_name: web
    build:
      context: ./web
      target: builder
      args:
        - GATSBY_API_SCHEME=http
        - GATSBY_API_HOST=127.0.0.1:3000
    volumes:
      - ./web/src:/home/node/app/src:delegated
      - ./web/scripts:/home/node/app/scripts:delegated
      - ./web/package.json:/home/node/app/package.json:delegated
      - ./web/yarn.lock:/home/node/app/yarn.lock:delegated
      - ./web/bsconfig.json:/home/node/app/bsconfig.json:delegated
      - ./web/gatsby-browser.js:/home/node/app/gatsby-browser.js:delegated
      - ./web/gatsby-config.js:/home/node/app/gatsby-config.js:delegated
      - ./web/gatsby-node.js:/home/node/app/gatsby-node.js:delegated
      - ./web/gatsby-ssr.js:/home/node/app/gatsby-ssr.js:delegated
      - ./web/jest.config.js:/home/node/app/jest.config.js:delegated
    ports:
      - "8000:8000"
  api:
    tty: true
    environment:
      # note: Networked service-to-service communication use the CONTAINER_PORT
      - ENDPOINT_PDFGEN=http://pdfgen:4000
    depends_on:
      - pdfgen
    command: sh ./scripts/startup.sh
    container_name: api
    build:
      context: ./api
    volumes:
      - ./api/src:/home/node/app/src:delegated
      - ./api/scripts:/home/node/app/scripts:delegated
      - ./api/package.json:/home/node/app/package.json:delegated
      - ./api/yarn.lock:/home/node/app/yarn.lock:delegated
      - ./api/nodemon.json:/home/node/app/nodemon.json:delegated
      - ./api/bsconfig.json:/home/node/app/bsconfig.json:delegated
    ports:
      - "3000:8080"
      - "3001:9229"
  pdfgen:
    tty: true
    privileged: true
    environment:
      - PORT=4000
    command: sh ./scripts/startup.sh
    build:
      context: ./pdfgen
    container_name: pdfgen
    volumes:
      - ./pdfgen/src:/home/node/app/src:delegated
      - ./pdfgen/scripts:/home/node/app/scripts:delegated
      - ./pdfgen/package.json:/home/node/app/package.json:delegated
      - ./pdfgen/yarn.lock:/home/node/app/yarn.lock:delegated
      - ./pdfgen/nodemon.json:/home/node/app/nodemon.json:delegated
      - ./pdfgen/bsconfig.json:/home/node/app/bsconfig.json:delegated
    ports:
      - "4000:4000"
      - "4001:9229"
