version: "3.7"

services:
  web:
    # truthy *tty* is necessary in order to get colored bsb output
    tty: true
    command: sh ./scripts/startup.sh
    container_name: web
    build:
      context: ./web
      target: builder
      args:
        - GATSBY_API_SCHEME=http
        - GATSBY_API_HOST=127.0.0.1:3000
    volumes:
      - ./web/src:/home/node/app/src:delegated
      - ./web/scripts:/home/node/app/scripts:delegated
      - ./web/__tests__:/home/node/app/__tests__:delegated
      - ./web/package.json:/home/node/app/package.json:delegated
      - ./web/yarn.lock:/home/node/app/yarn.lock:delegated
      - ./web/bsconfig.json:/home/node/app/bsconfig.json:delegated
      - ./web/gatsby-browser.js:/home/node/app/gatsby-browser.js:delegated
      - ./web/gatsby-config.js:/home/node/app/gatsby-config.js:delegated
      - ./web/gatsby-node.js:/home/node/app/gatsby-node.js:delegated
      - ./web/gatsby-ssr.js:/home/node/app/gatsby-ssr.js:delegated
      - ./web/jest.config.js:/home/node/app/jest.config.js:delegated
    ports:
      - "8000:8000"
  api:
    tty: true
    depends_on:
      - db
    command: yarn start
    environment:
      - PORT=4000
      - TYPEORM_HOST=db
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=postgres
      - TYPEORM_LOGGING=true
    container_name: api
    build:
      context: ./api
      target: builder
    volumes:
      - ./api/src:/home/node/app/src:delegated
      - ./api/scripts:/home/node/app/scripts:delegated
      - ./api/package.json:/home/node/app/package.json:delegated
      - ./api/yarn.lock:/home/node/app/yarn.lock:delegated
      - ./api/nodemon.json:/home/node/app/nodemon.json:delegated
      - ./api/ormconfig.yml:/home/node/app/ormconfig.yml:delegated
      - ./api/tsconfig.json:/home/node/app/tsconfig.json:delegated
      - ./api/.prettierrc.yaml:/home/node/app/.prettierrc.yaml:delegated
      - ./api/.eslintrc.yml:/home/node/app/.eslintrc.yml:delegated
      - ./api/.gitignore:/home/node/app/.gitignore:delegated
    ports:
      - "4000:4000"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  htmlgen:
    tty: true
    environment:
      - PORT=5000
    command: sh ./scripts/startup.sh
    container_name: htmlgen
    build:
      context: ./htmlgen
    volumes:
      - ./htmlgen/src:/home/node/app/src:delegated
      - ./htmlgen/scripts:/home/node/app/scripts:delegated
      - ./htmlgen/__tests__:/home/node/app/__tests__:delegated
      - ./htmlgen/package.json:/home/node/app/package.json:delegated
      - ./htmlgen/yarn.lock:/home/node/app/yarn.lock:delegated
      - ./htmlgen/nodemon.json:/home/node/app/nodemon.json:delegated
      - ./htmlgen/bsconfig.json:/home/node/app/bsconfig.json:delegated
    ports:
      - "5000:5000"
      - "3001:5001"
  pdfgen:
    tty: true
    privileged: true
    environment:
      - PORT=4000
    command: sh ./scripts/startup.sh
    build:
      context: ./pdfgen
    container_name: pdfgen
    volumes:
      - ./pdfgen/src:/home/node/app/src:delegated
      - ./pdfgen/scripts:/home/node/app/scripts:delegated
      - ./pdfgen/package.json:/home/node/app/package.json:delegated
      - ./pdfgen/yarn.lock:/home/node/app/yarn.lock:delegated
      - ./pdfgen/nodemon.json:/home/node/app/nodemon.json:delegated
      - ./pdfgen/bsconfig.json:/home/node/app/bsconfig.json:delegated
    ports:
      - "4000:4000"
      - "4001:9229"
