// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Url = require("../../src/utils/Url.js");
var Jest = require("@glennsl/bs-jest/src/jest.js");

var scheme = "https";

var host = "example.com";

var path = "test";

var qsComponents = /* array */[/* tuple */[
    "key1",
    "value1"
  ]];

Jest.describe("buildUrl", (function (param) {
        Jest.test("should return correct complete url", (function (param) {
                return Jest.Expect.toBe("https://example.com/test?key1=value1", Jest.Expect.expect(Url.make(scheme, host, path, qsComponents, /* () */0)));
              }));
        Jest.test("should return pathname + qs with no scheme", (function (param) {
                return Jest.Expect.toBe("/test?key1=value1", Jest.Expect.expect(Url.make(undefined, host, path, qsComponents, /* () */0)));
              }));
        Jest.test("should return pathname + qs with no host", (function (param) {
                return Jest.Expect.toBe("/test?key1=value1", Jest.Expect.expect(Url.make(scheme, undefined, path, qsComponents, /* () */0)));
              }));
        return Jest.test("should encode qs correctly", (function (param) {
                      return Jest.Expect.toBe("https://example.com/test?md=*%201%0A*%202%0A%2B-%3D%0A%60%60%60", Jest.Expect.expect(Url.make(scheme, host, path, /* array */[/* tuple */[
                                            "md",
                                            "* 1\n* 2\n+-=\n```"
                                          ]], /* () */0)));
                    }));
      }));

exports.scheme = scheme;
exports.host = host;
exports.path = path;
exports.qsComponents = qsComponents;
/*  Not a pure module */
