steps:
  # pull cached image
  # - name: "gcr.io/cloud-builders/docker"
  #   args:
  #     - "-c"
  #     - "docker pull gcr.io/$PROJECT_ID/pdfgen:latest || exit 0"
  # build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      # - "--cache-from"
      # - "gcr.io/$PROJECT_ID/pdfgen:latest"
      - "--build-arg"
      - "SCHEME=https"
      - "--build-arg"
      - "HOST=pdfgen-67xb7jfyla-ew.a.run.app"
      - "--build-arg"
      - "PORT=8080"
      # - "--tag
      # - "gcr.io/$PROJECT_ID/api:$SHORT_SHA
      - "--tag"
      - "gcr.io/$PROJECT_ID/pdfgen:latest"
      - "."
    timeout: 200s
images:
  - "gcr.io/$PROJECT_ID/pdfgen:latest"
  # - "gcr.io/$PROJECT_ID/pdfgen:$SHORT_SHA"
