steps:
  # pull cached image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/api:latest || exit 0"
  # build image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/api:latest"
      - "--build-arg"
      - "SCHEME=https"
      - "--build-arg"
      - "HOST=api-67xb7jfyla-ew.a.run.app"
      - "--build-arg"
      - "PORT=8080"
      # - "--tag"
      # - "gcr.io/$PROJECT_ID/api:$SHORT_SHA"
      - "--tag"
      - "gcr.io/$PROJECT_ID/api:latest"
      - "."
    timeout: 200s
  # deploy in multiple regions
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "api-europe-west1"
      - "--image"
      - "gcr.io/tech-resume/api"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "api-us-central1"
      - "--image"
      - "gcr.io/tech-resume/api"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
images:
  - "gcr.io/$PROJECT_ID/api:latest"
  # - "gcr.io/$PROJECT_ID/api:$SHORT_SHA"
