steps:
  # pull cached image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - "docker pull gcr.io/$PROJECT_ID/web:latest || exit 0"
  # build *builder* image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/web:latest"
      - "--target"
      - "builder"
      - "--build-arg"
      - "GATSBY_API_SCHEME=https"
      - "--build-arg"
      - "GATSBY_API_HOST=api-europe-west1-67xb7jfyla-ew.a.run.app"
      - "--tag"
      - "gcr.io/$PROJECT_ID/web-builder:latest"
      - "./web/"
    timeout: 720s # 12 minutes
  # test
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "gcr.io/$PROJECT_ID/web-builder:latest"
      - "sh"
      - "./scripts/test.sh"
    timeout: 300s
  # build final image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/web-builder:latest"
      - "--build-arg"
      - "GATSBY_API_SCHEME=https"
      - "--build-arg"
      - "GATSBY_API_HOST=api-europe-west1-67xb7jfyla-ew.a.run.app"
      - "--tag"
      - "gcr.io/$PROJECT_ID/web:$SHORT_SHA"
      - "--tag"
      - "gcr.io/$PROJECT_ID/web:latest"
      - "./web/"
    timeout: 720s # 12 minutes
  # deploy
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "gcr.io/$PROJECT_ID/web:latest"
      - "firebase deploy"
    timeout: 300s
timeout: 1200s
